#!/usr/bin/env python3
"""
generate_report.py
Produces a single self-contained Markdown report from the CSVs and images
generated by eval_conversations.py (Layer 1) and eval_layer2.py (Layer 2).

  Output: evaluation_report.md

Sections:
  1. Executive Summary
  2. Dataset Composition
  3. Layer 1 — Rule-Based Evaluation
       A. Warning Overview
       B. Structural Stats
       C. Lexical Signals
       D. First-Turn Info Density
       E. Breadth-First Bundling
       F. Persona Consistency
       G. Type-Specific Checks
       H. Outliers
  4. Layer 2 — LLM-as-Judge Evaluation
       A. Score Distributions
       B. Scores by Persona Attribute
       C. Bottom Conversations (priority review)
       D. Radar Overview
  5. Layer 1 → Layer 2 Correlation
  6. Metric Interpretation Guide

Each section is omitted gracefully when the underlying CSV is absent.
"""

import csv
import math
from collections import defaultdict
from pathlib import Path

BASE_DIR   = Path(__file__).parent
IMAGES_DIR = BASE_DIR / "images"
REPORT_PATH = BASE_DIR / "evaluation_report.md"

L1_CSV = BASE_DIR / "eval_results.csv"
L2_CSV = BASE_DIR / "eval_results_layer2.csv"

OUTLIER_THRESHOLD = 3   # must match eval_conversations.py

# ─────────────────────────────────────────────
#  CSV helpers
# ─────────────────────────────────────────────

def load_csv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with open(path, newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def fval(row: dict, key: str, fallback: float = 0.0) -> float:
    try:
        return float(row.get(key, fallback) or fallback)
    except (ValueError, TypeError):
        return fallback


def ival(row: dict, key: str, fallback: int = 0) -> int:
    try:
        return int(float(row.get(key, fallback) or fallback))
    except (ValueError, TypeError):
        return fallback


def bval(row: dict, key: str) -> bool:
    v = str(row.get(key, "")).strip().lower()
    return v in ("true", "1", "yes")


def mean(vals: list[float]) -> float:
    return sum(vals) / len(vals) if vals else 0.0


def stdev(vals: list[float]) -> float:
    if len(vals) < 2:
        return 0.0
    m = mean(vals)
    return math.sqrt(sum((x - m) ** 2 for x in vals) / len(vals))


def pct_str(n: int, total: int) -> str:
    if total == 0:
        return "0 (0%)"
    return f"{n} ({100 * n / total:.0f}%)"


def fmt(v: float, decimals: int = 2) -> str:
    return f"{v:.{decimals}f}"


def image_ref(name: str) -> str:
    """Return a relative markdown image link."""
    return f"![{name}](images/{name})"

# ─────────────────────────────────────────────
#  Report builder
# ─────────────────────────────────────────────

def build_report(l1_rows: list[dict], l2_rows: list[dict]) -> str:
    lines: list[str] = []

    def h(level: int, text: str):
        lines.append(f"\n{'#' * level} {text}\n")

    def para(text: str):
        lines.append(text + "\n")

    def rule():
        lines.append("---\n")

    has_l1 = bool(l1_rows)
    has_l2 = bool(l2_rows)

    n_l1 = len(l1_rows)
    n_l2 = len([r for r in l2_rows if not r.get("parse_error")])

    # ── Title ─────────────────────────────────────────────────────────────────
    lines.append("# Synthetic Conversation Evaluation Report\n")
    lines.append(
        "> **Layer 1** — rule-based heuristic checks (eval_conversations.py)  \n"
        "> **Layer 2** — LLM-as-judge behavioural scoring (eval_layer2.py)\n"
    )
    rule()

    # ── 1. Executive Summary ──────────────────────────────────────────────────
    h(2, "1. Executive Summary")

    if has_l1:
        outliers   = [r for r in l1_rows if bval(r, "is_outlier")]
        warn_counts = [ival(r, "warning_count") for r in l1_rows]
        avg_warns  = mean([float(w) for w in warn_counts])

    if has_l2:
        valid_l2 = [r for r in l2_rows if not r.get("parse_error")]
        overall_scores = [fval(r, "overall_score") for r in valid_l2 if fval(r, "overall_score") > 0]
        avg_overall = mean(overall_scores)
        model_used = valid_l2[0].get("model_used", "?") if valid_l2 else "?"

    summary_rows = []
    if has_l1:
        summary_rows += [
            ("Conversations evaluated (Layer 1)", str(n_l1)),
            ("Avg warnings per conversation", fmt(avg_warns)),
            (f"Outliers (≥ {OUTLIER_THRESHOLD} warnings)", pct_str(len(outliers), n_l1)),
        ]
    if has_l2:
        summary_rows += [
            ("Conversations scored (Layer 2)", str(n_l2)),
            ("Avg overall score (1–5 scale)", fmt(avg_overall)),
            ("Judge model", model_used),
        ]

    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    for label, value in summary_rows:
        lines.append(f"| {label} | {value} |")
    lines.append("")

    if has_l1 and has_l2:
        quality_label = (
            "**Good** — most conversations score above 3.5 on the human-likeness scale."
            if avg_overall >= 3.5 else
            "**Moderate** — meaningful room for improvement; consider regenerating low-scoring conversations."
            if avg_overall >= 2.5 else
            "**Needs work** — average score below 2.5; systematic issues present."
        )
        para(f"Overall quality assessment: {quality_label}")

    rule()

    # ── 2. Dataset Composition ─────────────────────────────────────────────────
    h(2, "2. Dataset Composition")

    if has_l1:
        type_counts: dict[str, int] = defaultdict(int)
        for r in l1_rows:
            type_counts[r.get("dataset_type", "unknown")] += 1

        lines.append("| Dataset Type | Count | % of Total |")
        lines.append("|--------------|-------|------------|")
        for dtype in sorted(type_counts):
            n = type_counts[dtype]
            lines.append(f"| `{dtype}` | {n} | {100 * n / n_l1:.0f}% |")
        lines.append(f"| **Total** | **{n_l1}** | 100% |")
        lines.append("")

        # Persona attribute distributions
        for attr, label in [
            ("emotional_state",     "Emotional State"),
            ("knowledge_level",     "Knowledge Level"),
            ("communication_style", "Communication Style"),
            ("goal_clarity",        "Goal Clarity"),
        ]:
            dist: dict[str, int] = defaultdict(int)
            for r in l1_rows:
                dist[r.get(attr, "?")] += 1
            vals_sorted = sorted(dist.items(), key=lambda x: -x[1])
            cell = "  |  ".join(f"`{k}` {v}" for k, v in vals_sorted)
            lines.append(f"**{label}:** {cell}  ")
        lines.append("")
    else:
        para("_Layer 1 CSV not found — dataset composition unavailable._")

    rule()

    # ── 3. Layer 1 — Rule-Based Evaluation ───────────────────────────────────
    h(2, "3. Layer 1 — Rule-Based Evaluation")

    if not has_l1:
        para("_`eval_results.csv` not found. Run `eval_conversations.py` first._")
    else:
        # ── 3A. Warning Overview ──────────────────────────────────────────────
        h(3, "3A. Warning Overview")
        para(
            "Each conversation is checked across five dimensions (A–E) plus "
            "type-specific checks (F). Each triggered check adds one warning. "
            "Conversations with ≥ 3 warnings are flagged as outliers."
        )
        para(image_ref("01_warning_summary.png"))

        # Warning frequency table
        WARNING_META = {
            "HIGH_AVG_TURN_LENGTH":               "A – High avg turn length (> 30 words)",
            "LOW_LENGTH_VARIANCE":                "A – Low turn-length variance (stddev < 3)",
            "CERTAINTY_EXCEEDS_HEDGING":          "B – Certainty rate > hedge rate (uncertain persona)",
            "ZERO_HEDGING_FOR_UNCERTAIN_SCENARIO":"B – Zero hedging in uncertain scenario",
            "INFO_DUMP_TURN1":                    "C – All 3 facts in turn 1 (info dump)",
            "BREADTH_FIRST_BUNDLING":             "D – Breadth-first topic bundling",
            "MISSING_FRUSTRATION_MARKERS":        "E – Missing frustration markers",
            "UNEXPECTED_FRUSTRATION":             "E – Unexpected frustration (calm persona)",
            "MISSING_STRONG_FRUSTRATION":         "E – Missing strong frustration (very_upset/escalating)",
            "NOVICE_JARGON":                      "E – Novice used jargon before agent",
            "DIRECT_STYLE_BUT_LONG_TURNS":        "E – Direct style but long turns",
            "INDIRECT_STYLE_BUT_VERY_SHORT":      "E – Indirect style but very short turns",
            "DROPOUT_TOO_EARLY":                  "F – Dropout too early (< 3 turns)",
            "DROPOUT_NOT_PLAUSIBLE":              "F – Dropout language absent",
            "MISSING_ESCALATION_ARC":             "F – Missing escalation arc",
            "PRIOR_BELIEF_ABSENT":                "F – Prior belief absent from transcript",
            "BELIEF_SILENTLY_DROPPED":            "F – Prior belief silently dropped",
            "ERROR_NOT_CAUGHT":                   "F – Planted agent error not caught",
            "USER_CAUGHT_ERROR_LABEL_MISMATCH":   "F – user_caught_error label mismatch",
        }

        warn_counts: dict[str, int] = defaultdict(int)
        for r in l1_rows:
            seen: set[str] = set()
            for w in r.get("warnings", "").split(" | "):
                for key in WARNING_META:
                    if w.startswith(key) and key not in seen:
                        warn_counts[key] += 1
                        seen.add(key)

        triggered = [(k, v) for k, v in warn_counts.items() if v > 0]
        triggered.sort(key=lambda x: -x[1])

        if triggered:
            lines.append("| Warning | Conversations Flagged | % |")
            lines.append("|---------|----------------------|---|")
            for key, count in triggered:
                lines.append(
                    f"| {WARNING_META[key]} | {count} | {100 * count / n_l1:.0f}% |"
                )
            lines.append("")

        # ── 3B. Structural Stats ──────────────────────────────────────────────
        h(3, "3B. Structural Stats")
        para(
            "Measures of customer turn length and count per conversation. "
            "Very long average turns (> 30 words) or unnaturally uniform turn lengths "
            "(stddev < 3.0) are flagged."
        )
        para(image_ref("02_structural_stats.png"))

        means   = [fval(r, "words_mean")         for r in l1_rows]
        stddevs = [fval(r, "words_stddev")        for r in l1_rows]
        nturns  = [fval(r, "num_customer_turns")  for r in l1_rows]
        p90s    = [fval(r, "words_p90")           for r in l1_rows]

        hi_avg   = sum(1 for v in means   if v > 30)
        lo_var   = sum(1 for r in l1_rows if fval(r, "words_stddev") < 3.0
                       and ival(r, "num_customer_turns") >= 3)

        lines.append("| Metric | Mean | Min | Max | Stdev |")
        lines.append("|--------|------|-----|-----|-------|")
        for label, vals in [
            ("Avg words / turn",       means),
            ("Turn-length stddev",      stddevs),
            ("Customer turns / conv",   nturns),
            ("P90 words / turn",        p90s),
        ]:
            lines.append(
                f"| {label} | {fmt(mean(vals))} | {fmt(min(vals))} "
                f"| {fmt(max(vals))} | {fmt(stdev(vals))} |"
            )
        lines.append("")
        lines.append(f"- Conversations with HIGH_AVG_TURN_LENGTH (> 30 words): **{pct_str(hi_avg, n_l1)}**")
        lines.append(f"- Conversations with LOW_LENGTH_VARIANCE (stddev < 3.0): **{pct_str(lo_var, n_l1)}**")
        lines.append("")

        # ── 3C. Lexical Signals ───────────────────────────────────────────────
        h(3, "3C. Lexical Signals — Hedging vs Over-Certainty")
        para(
            'Real humans hedge uncertainty ("I think", "not sure", "maybe"). '
            'LLM-generated users over-commit with words like "definitely", "absolutely", "certainly" '
            "(Wang et al. 2025). A positive **hedge − certainty** score is human-like."
        )
        para(image_ref("03_lexical_signals.png"))

        hedge_rates = [fval(r, "hedge_rate")          for r in l1_rows]
        cert_rates  = [fval(r, "certainty_rate")       for r in l1_rows]
        hmc         = [fval(r, "hedge_minus_certainty") for r in l1_rows]
        cert_exceed = sum(1 for r in l1_rows
                          if "CERTAINTY_EXCEEDS_HEDGING" in r.get("warnings", ""))
        zero_hedge  = sum(1 for r in l1_rows
                          if "ZERO_HEDGING_FOR_UNCERTAIN_SCENARIO" in r.get("warnings", ""))

        lines.append("| Metric | Mean | Min | Max |")
        lines.append("|--------|------|-----|-----|")
        for label, vals in [
            ("Hedge rate (phrases / turn)",     hedge_rates),
            ("Certainty rate (phrases / turn)", cert_rates),
            ("Hedge − Certainty",               hmc),
        ]:
            lines.append(
                f"| {label} | {fmt(mean(vals), 3)} | {fmt(min(vals), 3)} | {fmt(max(vals), 3)} |"
            )
        lines.append("")
        lines.append(f"- Certainty > Hedging (uncertain persona): **{pct_str(cert_exceed, n_l1)}**")
        lines.append(f"- Zero hedging in uncertain scenario: **{pct_str(zero_hedge, n_l1)}**")
        lines.append("")

        # ── 3D. First-Turn Info Density ────────────────────────────────────────
        h(3, "3D. First-Turn Information Density")
        para(
            "Checks how many of the three key facts — merchant, amount, transaction date — "
            "the customer volunteers unprompted in their very first turn. "
            "Volunteering all three at once is LLM-like; real customers drip information "
            "gradually."
        )
        para(image_ref("04_info_density.png"))

        facts_dist: dict[int, int] = defaultdict(int)
        for r in l1_rows:
            facts_dist[ival(r, "facts_in_turn1")] += 1

        lines.append("| Facts in Turn 1 | Count | % | Assessment |")
        lines.append("|-----------------|-------|---|------------|")
        assessments = ["Human-like", "Acceptable", "Borderline", "LLM-like (flag)"]
        for i in range(4):
            count = facts_dist.get(i, 0)
            lines.append(
                f"| {i} | {count} | {100 * count / n_l1:.0f}% | {assessments[i]} |"
            )
        lines.append("")

        info_dumps = sum(1 for r in l1_rows if ival(r, "facts_in_turn1") == 3)
        para(f"Info-dump rate (all 3 facts in turn 1): **{pct_str(info_dumps, n_l1)}**")

        # ── 3E. Breadth-First Bundling ─────────────────────────────────────────
        h(3, "3E. Breadth-First Topic Bundling")
        para(
            "Real users raise one concern at a time (depth-first). "
            "LLM-generated users bundle multiple concerns — dispute + card cancel + refund ETA — "
            "into a single message (breadth-first). Flagged when max concern-categories in any "
            "single turn ≥ 3, or when ≥ 2 turns contain multiple categories."
        )
        para(image_ref("05_breadth_first_bundling.png"))

        bf_flagged   = sum(1 for r in l1_rows if bval(r, "breadth_first_flag"))
        max_cats     = [ival(r, "max_categories_per_turn")   for r in l1_rows]
        multi_turns  = [ival(r, "turns_with_multi_category") for r in l1_rows]

        lines.append("| Metric | Mean | Max |")
        lines.append("|--------|------|-----|")
        lines.append(f"| Max concern-categories in one turn | {fmt(mean(max_cats))} | {max(max_cats)} |")
        lines.append(f"| Turns with 2+ concern categories   | {fmt(mean(multi_turns))} | {max(multi_turns)} |")
        lines.append("")
        para(f"Breadth-first flagged: **{pct_str(bf_flagged, n_l1)}**")

        # ── 3F. Persona Consistency ────────────────────────────────────────────
        h(3, "3F. Persona Consistency")
        para(
            "Checks whether the generated customer's language actually reflects their "
            "assigned persona attributes: emotional state, knowledge level, and communication style."
        )
        para(image_ref("06_persona_consistency.png"))

        persona_checks = [
            ("MISSING_FRUSTRATION_MARKERS",    "Missing frustration markers (mildly_frustrated persona)"),
            ("UNEXPECTED_FRUSTRATION",         "Unexpected frustration (calm persona)"),
            ("MISSING_STRONG_FRUSTRATION",     "Missing strong frustration (very_upset / escalating)"),
            ("NOVICE_JARGON",                  "Novice customer used banking jargon before agent"),
            ("DIRECT_STYLE_BUT_LONG_TURNS",    "Direct style but long turns (> 25 words avg)"),
            ("INDIRECT_STYLE_BUT_VERY_SHORT",  "Indirect style but very short turns (< 6 words avg)"),
        ]

        lines.append("| Check | Flagged | % |")
        lines.append("|-------|---------|---|")
        for key, label in persona_checks:
            count = sum(1 for r in l1_rows if key in r.get("warnings", ""))
            lines.append(f"| {label} | {count} | {100 * count / n_l1:.0f}% |")
        lines.append("")

        # ── 3G. Type-Specific Checks ───────────────────────────────────────────
        type_checks = [
            ("DROPOUT_TOO_EARLY",           "failure",  "Dropout too early (< 3 turns)"),
            ("DROPOUT_NOT_PLAUSIBLE",       "failure",  "Dropout language absent from final turn"),
            ("MISSING_ESCALATION_ARC",      "failure",  "Missing escalation arc (impatience/escalation_exit)"),
            ("PRIOR_BELIEF_ABSENT",         "type_a",   "Wrong prior belief absent from transcript"),
            ("BELIEF_SILENTLY_DROPPED",     "type_a",   "Prior belief silently dropped mid-conversation"),
            ("ERROR_NOT_CAUGHT",            "type_b",   "Planted agent error not caught by customer"),
            ("USER_CAUGHT_ERROR_LABEL_MISMATCH", "type_b", "user_caught_error label mismatch vs transcript"),
        ]

        has_any_type = any(
            any(k in r.get("warnings", "") for k, _, __ in type_checks)
            for r in l1_rows
        )

        if has_any_type:
            h(3, "3G. Type-Specific Checks")
            para(
                "Additional checks applied only to conversations of the relevant dataset type."
            )

            lines.append("| Check | Type | Flagged | % |")
            lines.append("|-------|------|---------|---|")
            for key, dtype, label in type_checks:
                subset = [r for r in l1_rows if r.get("dataset_type") == dtype]
                if not subset:
                    continue
                count = sum(1 for r in subset if key in r.get("warnings", ""))
                lines.append(
                    f"| {label} | `{dtype}` | {count}/{len(subset)} | "
                    f"{100 * count / len(subset):.0f}% |"
                )
            lines.append("")

        # ── 3H. Outliers ──────────────────────────────────────────────────────
        h(3, "3H. Outlier Summary")
        para(
            f"Conversations with ≥ {OUTLIER_THRESHOLD} warnings are flagged as outliers "
            "and are priority candidates for manual review or regeneration."
        )
        para(image_ref("07_outlier_summary.png"))

        outlier_rows = sorted(
            [r for r in l1_rows if bval(r, "is_outlier")],
            key=lambda r: -ival(r, "warning_count"),
        )

        if not outlier_rows:
            para(f"✓ No outliers — all {n_l1} conversations have < {OUTLIER_THRESHOLD} warnings.")
        else:
            para(f"**{len(outlier_rows)} outlier conversation(s)** out of {n_l1}:")
            lines.append(
                "| Conv | Warnings | Emotional State | Knowledge | Style | Warning Summary |"
            )
            lines.append("|------|----------|-----------------|-----------|-------|-----------------|")
            for r in outlier_rows:
                warns = r.get("warnings", "").replace("|", "·")[:120]
                lines.append(
                    f"| {ival(r, 'conv_idx'):03d} "
                    f"| {ival(r, 'warning_count')} "
                    f"| {r.get('emotional_state', '')} "
                    f"| {r.get('knowledge_level', '')} "
                    f"| {r.get('communication_style', '')} "
                    f"| {warns} |"
                )
            lines.append("")

    rule()

    # ── 4. Layer 2 — LLM-as-Judge Evaluation ─────────────────────────────────
    h(2, "4. Layer 2 — LLM-as-Judge Evaluation")

    if not has_l2:
        para("_`eval_results_layer2.csv` not found. Run `eval_layer2.py` first._")
    else:
        valid_l2 = [r for r in l2_rows if not r.get("parse_error")]
        n_valid  = len(valid_l2)

        DIMENSIONS = ["depth_first", "uncertainty", "info_drip", "pragmatic", "persona"]
        DIM_LABELS = {
            "depth_first": "Depth-First Questioning",
            "uncertainty": "Appropriate Uncertainty",
            "info_drip":   "Natural Info Drip",
            "pragmatic":   "Pragmatic Naturalness",
            "persona":     "Persona Fidelity",
            "overall":     "Overall",
        }

        para(
            "Each conversation is scored 1–5 on five behavioural dimensions by an LLM judge "
            "(**1 = clearly LLM-like, 5 = clearly human-like**), grounded in Wang et al. (2025), "
            "Mannekote et al. (2025), and Chen et al. (2024). "
            f"Judge model: `{valid_l2[0].get('model_used', '?') if valid_l2 else '?'}`."
        )

        # ── 4A. Score Distributions ───────────────────────────────────────────
        h(3, "4A. Score Distributions")
        para(image_ref("08_score_distributions.png"))

        all_dims = DIMENSIONS + ["overall"]
        lines.append("| Dimension | Mean | Min | Max | Stdev |")
        lines.append("|-----------|------|-----|-----|-------|")
        for dim in all_dims:
            attr = f"{dim}_score" if dim != "overall" else "overall_score"
            vals = [fval(r, attr) for r in valid_l2 if fval(r, attr) > 0]
            if vals:
                label = DIM_LABELS.get(dim, dim)
                bold = "**" if dim == "overall" else ""
                lines.append(
                    f"| {bold}{label}{bold} "
                    f"| {bold}{fmt(mean(vals))}{bold} "
                    f"| {fmt(min(vals), 1)} "
                    f"| {fmt(max(vals), 1)} "
                    f"| {fmt(stdev(vals))} |"
                )
        lines.append("")

        # Weakest dimension
        dim_means = {}
        for dim in DIMENSIONS:
            vals = [fval(r, f"{dim}_score") for r in valid_l2 if fval(r, f"{dim}_score") > 0]
            if vals:
                dim_means[dim] = mean(vals)
        if dim_means:
            weakest = min(dim_means, key=dim_means.get)
            strongest = max(dim_means, key=dim_means.get)
            para(
                f"**Weakest dimension:** {DIM_LABELS[weakest]} "
                f"(μ = {fmt(dim_means[weakest])})  \n"
                f"**Strongest dimension:** {DIM_LABELS[strongest]} "
                f"(μ = {fmt(dim_means[strongest])})"
            )

        # Type-specific dimension summary
        type_specific_dims = [
            ("dropout_authenticity_score",   "failure", "Dropout Authenticity"),
            ("prior_belief_coherence_score", "type_a",  "Prior Belief Coherence"),
            ("error_catch_quality_score",    "type_b",  "Error Catch Quality"),
            ("pushback_naturalness_score",   "type_b",  "Pushback Naturalness"),
        ]

        type_specific_data = []
        for attr, dtype, label in type_specific_dims:
            subset = [r for r in valid_l2 if r.get("dataset_type") == dtype]
            vals = [fval(r, attr) for r in subset if fval(r, attr) > 0]
            if vals:
                type_specific_data.append((label, dtype, vals))

        if type_specific_data:
            h(4, "Type-Specific Dimension Scores")
            lines.append("| Dimension | Type | Mean | Min | Max |")
            lines.append("|-----------|------|------|-----|-----|")
            for label, dtype, vals in type_specific_data:
                lines.append(
                    f"| {label} | `{dtype}` "
                    f"| {fmt(mean(vals))} | {fmt(min(vals), 1)} | {fmt(max(vals), 1)} |"
                )
            lines.append("")

        # ── 4B. Scores by Persona ─────────────────────────────────────────────
        h(3, "4B. Scores by Persona Attribute")
        para(
            "Heatmap showing which persona attribute combinations produce the lowest "
            "human-likeness scores — the hardest configurations to generate realistically."
        )
        para(image_ref("09_scores_by_persona.png"))

        for attr, label in [
            ("emotional_state",     "Emotional State"),
            ("knowledge_level",     "Knowledge Level"),
            ("communication_style", "Communication Style"),
        ]:
            attr_vals = sorted(set(r.get(attr, "") for r in valid_l2 if r.get(attr)))
            if not attr_vals:
                continue

            lines.append(f"**{label}** — mean overall score by value:")
            lines.append("")
            lines.append("| Value | Mean Overall | Weakest Dimension |")
            lines.append("|-------|-------------|-------------------|")
            for av in attr_vals:
                subset = [r for r in valid_l2 if r.get(attr) == av]
                ov = [fval(r, "overall_score") for r in subset if fval(r, "overall_score") > 0]
                if not ov:
                    continue
                # find weakest dim for this slice
                dm = {}
                for dim in DIMENSIONS:
                    dv = [fval(r, f"{dim}_score") for r in subset if fval(r, f"{dim}_score") > 0]
                    if dv:
                        dm[dim] = mean(dv)
                weakest_dim = min(dm, key=dm.get) if dm else "—"
                lines.append(
                    f"| `{av}` | {fmt(mean(ov))} "
                    f"| {DIM_LABELS.get(weakest_dim, weakest_dim)} "
                    f"({fmt(dm.get(weakest_dim, 0))}) |"
                )
            lines.append("")

        # ── 4C. Bottom Conversations ───────────────────────────────────────────
        h(3, "4C. Bottom Conversations — Priority Review List")
        para(
            "The 15 lowest-scoring conversations by overall score. "
            "These are the top candidates for manual review or regeneration."
        )
        para(image_ref("11_bottom_conversations.png"))

        bottom = sorted(
            [r for r in valid_l2 if fval(r, "overall_score") > 0],
            key=lambda r: fval(r, "overall_score"),
        )[:15]

        if bottom:
            lines.append(
                "| Conv | Type | Overall | D | U | I | P | Pe | Standout Issue |"
            )
            lines.append(
                "|------|------|---------|---|---|---|---|----|----------------|"
            )
            for r in bottom:
                issue = r.get("standout_issue", "")[:80]
                lines.append(
                    f"| {ival(r, 'conv_idx'):03d} "
                    f"| `{r.get('dataset_type', '')}` "
                    f"| {fmt(fval(r, 'overall_score'))} "
                    f"| {fmt(fval(r, 'depth_first_score'), 0)} "
                    f"| {fmt(fval(r, 'uncertainty_score'), 0)} "
                    f"| {fmt(fval(r, 'info_drip_score'), 0)} "
                    f"| {fmt(fval(r, 'pragmatic_score'), 0)} "
                    f"| {fmt(fval(r, 'persona_score'), 0)} "
                    f"| {issue} |"
                )
            lines.append("")
            lines.append(
                "> **D** = Depth-First  **U** = Uncertainty  **I** = Info Drip  "
                "**P** = Pragmatic  **Pe** = Persona Fidelity\n"
            )

        # ── 4D. Radar Overview ─────────────────────────────────────────────────
        h(3, "4D. Radar Overview")
        para(
            "Single-glance quality card: mean score per dimension broken out by "
            "emotional state. Outer edge = 5 (fully human-like)."
        )
        para(image_ref("12_radar_overview.png"))

    rule()

    # ── 5. Layer 1 → Layer 2 Correlation ─────────────────────────────────────
    if has_l1 and has_l2:
        h(2, "5. Layer 1 → Layer 2 Correlation")
        para(
            "Validates whether the rule-based heuristics predict the LLM judge's "
            "behavioural scores. Strong correlation confirms the heuristics measure "
            "the same quality signals."
        )
        para(image_ref("10_layer1_vs_layer2_correlation.png"))

        # Build a merged lookup
        l1_by_key = {
            (ival(r, "conv_idx"), r.get("dataset_type", "")): r
            for r in l1_rows
        }
        valid_l2_merged = [
            r for r in valid_l2
            if (ival(r, "conv_idx"), r.get("dataset_type", "")) in l1_by_key
        ]

        if valid_l2_merged:
            pairs = [
                ("hedge_minus_certainty", "uncertainty_score",
                 "Hedge − Certainty → Uncertainty Score"),
                ("info_density_score", "info_drip_score",
                 "Info Density (L1) → Info Drip Score (L2)"),
                ("words_mean", "pragmatic_score",
                 "Avg Turn Length → Pragmatic Naturalness"),
            ]

            lines.append("| Heuristic Pair | Pearson r | Interpretation |")
            lines.append("|----------------|-----------|----------------|")

            for l1_key, l2_attr, label in pairs:
                xs, ys = [], []
                for r in valid_l2_merged:
                    l1 = l1_by_key[(ival(r, "conv_idx"), r.get("dataset_type", ""))]
                    try:
                        xs.append(float(l1[l1_key]))
                        ys.append(fval(r, l2_attr))
                    except (KeyError, ValueError):
                        pass

                if len(xs) > 3:
                    mx, my = mean(xs), mean(ys)
                    num = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
                    denom = math.sqrt(
                        sum((x - mx) ** 2 for x in xs) *
                        sum((y - my) ** 2 for y in ys)
                    )
                    r_val = num / denom if denom else 0.0
                    interp = (
                        "Strong" if abs(r_val) >= 0.5 else
                        "Moderate" if abs(r_val) >= 0.3 else
                        "Weak"
                    )
                    direction = "positive" if r_val >= 0 else "negative"
                    lines.append(
                        f"| {label} | {fmt(r_val, 3)} | {interp} {direction} |"
                    )
            lines.append("")

        rule()

    # ── 6. Metric Interpretation Guide ────────────────────────────────────────
    h(2, "6. Metric Interpretation Guide")

    lines.append("""
### Layer 1 — Rule-Based Signals

| Dimension | What it measures | LLM-like pattern |
|-----------|-----------------|------------------|
| **A – Structural** | Turn length and length variance | Very long turns (> 30 words), uniformly sized turns |
| **B – Lexical** | Hedging vs over-certainty language | Certainty rate > hedge rate for uncertain personas |
| **C – Info Density** | Facts volunteered in turn 1 | All 3 facts (merchant + amount + date) front-loaded |
| **D – Breadth-first** | Multi-concern bundling per turn | 3+ concern categories in one message |
| **E – Persona** | Emotional, knowledge, style consistency | Calm persona with frustration markers; novice using jargon |
| **F – Type-specific** | Dataset-type contracts | Failure dropout language absent; error not caught |

### Layer 2 — LLM Judge Dimensions (1 = LLM-like, 5 = Human-like)

| Score | Depth-First | Uncertainty | Info Drip | Pragmatic | Persona Fidelity |
|-------|------------|-------------|-----------|-----------|-----------------|
| **5** | One concern at a time, never bundles | Hedging matches scenario certainty | Reveals facts only when prompted | Sounds like a real caller | Assigned attributes clearly manifest |
| **3** | Occasional bundling | Mostly appropriate | Mixed — some proactive sharing | 1–2 formulaic turns | Some attributes present |
| **1** | Bundles dispute + card + refund in first message | Uncertain scenario but "I definitely didn't…" | All 3 facts front-loaded | Reads like a script | Persona is undetectable |

### Weighted Overall Score

The overall score is a weighted average of dimension scores. Weights vary by
dataset type (e.g. `failure` conversations weight **dropout_authenticity** more
heavily; `type_b` conversations weight **error_catch_quality** and
**pushback_naturalness**). See `eval_layer2.py → DIMENSION_WEIGHTS` for exact values.

### Action Thresholds

| Score Range | Recommendation |
|-------------|---------------|
| ≥ 4.0 | Publish / use as-is |
| 3.0 – 3.9 | Spot-check; acceptable for most purposes |
| 2.0 – 2.9 | Review and selectively regenerate |
| < 2.0 | Regenerate; systematic generation failure |
""")

    return "\n".join(lines)


# ─────────────────────────────────────────────
#  Main
# ─────────────────────────────────────────────

def main():
    print("Loading CSVs …")
    l1_rows = load_csv(L1_CSV)
    l2_rows = load_csv(L2_CSV)

    if not l1_rows and not l2_rows:
        print("  ⚠  Neither eval_results.csv nor eval_results_layer2.csv found.")
        print("     Run eval_conversations.py and/or eval_layer2.py first.")
        return

    if l1_rows:
        print(f"  Layer 1: {len(l1_rows)} rows from {L1_CSV.name}")
    else:
        print("  Layer 1: not found — L1 sections will be skipped.")

    if l2_rows:
        valid = sum(1 for r in l2_rows if not r.get("parse_error"))
        print(f"  Layer 2: {len(l2_rows)} rows ({valid} valid) from {L2_CSV.name}")
    else:
        print("  Layer 2: not found — L2 sections will be skipped.")

    print("Building report …")
    report = build_report(l1_rows, l2_rows)

    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"\n✓  Report written to: {REPORT_PATH}")
    print(f"   Length: {len(report):,} characters / ~{len(report.splitlines())} lines")


if __name__ == "__main__":
    main()
